sudo: required

language: csharp

services:
  - docker

before_install:
- docker build -t sylhare/hello-dotnet:v1 .
- docker run --name dotnetapp -d -p 5000:80 sylhare/hello-dotnet:v1
- docker ps| grep dotnet

script:
- curl localhost:5000