sudo: required

language: csharp

services:
  - docker

before_install:
- pwd
- docker pull sylhare/hello-dotnet:v3

before_script:
- pwd

script:
- pwd
- cd bin/Release/netcoreapp2.0/publish/
- docker build -t sylhare/hello-dotnet:latest .
- docker run --name dotnetapp -d -p 5000:80 sylhare/hello-dotnet:latest
- docker ps| grep dotnet
- sleep 10
- curl localhost:5000
- docker stop dotnetapp