sudo: required

language: csharp

services:
  - docker

before_install:
- docker build -t sylhare/hello-dotnet:latest .
- docker run --name dotnetapp -d -p 5000:80 sylhare/hello-dotnet:latest
- docker ps| grep dotnet

script:
- sleep 10
- curl localhost:5000